import { NextResponse } from "next/server";
import { getCacheSettingsServer } from "@/lib/cache-settings-server";

/**
 * Serves /sw.js dynamically instead of as a static /public file — same
 * reasoning as src/app/favicon.ico/route.ts: this needs to read
 * cache_settings (Admin → Cache → Browser Cache) on every request so the
 * "Enable service worker" toggle and cache-version bump take effect for
 * every visitor without a redeploy.
 *
 * When disabled, this does NOT simply stop serving a worker — a browser
 * that already installed one from an earlier visit would keep running it
 * forever with no way to know it should stop. Instead it serves a tiny
 * "kill switch" worker: unregister itself, clear every cache it created,
 * and reload any open tab so it detaches immediately. This is the
 * standard fix for the classic service-worker footgun of a stale worker
 * outliving the feature that shipped it.
 *
 * Caching strategy when enabled:
 *   - Non-GET requests, and anything under /admin or /api: never
 *     intercepted — always goes straight to the network.
 *   - Page navigations: network-first (so content is never stale),
 *     falling back to a minimal offline notice if the network is down.
 *   - Same-origin /_next/static assets: cache-first — Next.js itself
 *     content-hashes these and marks them immutable, so a cached copy is
 *     never wrong.
 *   - Any other `image` request (including cross-origin Supabase Storage
 *     thumbnails/media): cache-first. Every upload path in
 *     admin-content.ts is stamped with the upload time, so a given URL's
 *     content never changes — safe to treat as immutable at the SW layer
 *     even though the HTTP Cache-Control on some of those buckets is
 *     shorter (see migration 0033's header comment).
 *   - Everything else: network, uncached.
 */

export const dynamic = "force-dynamic";

function buildDisabledWorker(): string {
  return `// Cache is disabled in Admin → Cache → Browser Cache.
// This worker's only job is to remove itself and everything it cached.
self.addEventListener("install", () => self.skipWaiting());
self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.map((key) => caches.delete(key))))
      .then(() => self.registration.unregister())
      .then(() => self.clients.matchAll())
      .then((clients) => clients.forEach((client) => client.navigate(client.url)))
  );
});
`;
}

function buildActiveWorker(cacheName: string): string {
  return `// Generated by src/app/sw.js/route.ts — cache name: ${cacheName}
const CACHE_NAME = ${JSON.stringify(cacheName)};
const OFFLINE_BODY =
  "<!doctype html><meta charset=utf-8><title>Offline</title>" +
  "<p style='font:16px system-ui;padding:2rem;text-align:center'>" +
  "You're offline and this page hasn't been cached yet.</p>";

self.addEventListener("install", () => self.skipWaiting());

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key))))
      .then(() => self.clients.claim())
  );
});

async function cacheFirst(request) {
  const cached = await caches.match(request);
  if (cached) return cached;
  const response = await fetch(request);
  if (response && response.status === 200) {
    const cache = await caches.open(CACHE_NAME);
    cache.put(request, response.clone());
  }
  return response;
}

async function networkFirst(request) {
  try {
    return await fetch(request);
  } catch (err) {
    const cached = await caches.match(request);
    if (cached) return cached;
    if (request.mode === "navigate") {
      return new Response(OFFLINE_BODY, { status: 503, headers: { "Content-Type": "text/html" } });
    }
    throw err;
  }
}

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  if (url.origin === self.location.origin && (url.pathname.startsWith("/admin") || url.pathname.startsWith("/api"))) {
    return;
  }

  if (url.origin === self.location.origin && url.pathname.startsWith("/_next/static")) {
    event.respondWith(cacheFirst(request));
    return;
  }

  if (request.destination === "image") {
    event.respondWith(cacheFirst(request));
    return;
  }

  if (request.mode === "navigate") {
    event.respondWith(networkFirst(request));
  }
});
`;
}

export async function GET() {
  const settings = await getCacheSettingsServer();

  const body = settings.serviceWorkerEnabled
    ? buildActiveWorker(`mofigames-sw-v${settings.serviceWorkerCacheVersion}`)
    : buildDisabledWorker();

  return new NextResponse(body, {
    headers: {
      "Content-Type": "application/javascript; charset=utf-8",
      // A service worker file must never be cached by the browser's HTTP
      // cache — it's the one file that has to be re-checked on every
      // navigation so an admin's enable/disable toggle and version bump
      // can actually take effect. See the "service_worker" check in
      // /api/admin/cache/inspect.
      "Cache-Control": "no-cache, no-store, must-revalidate",
      "Service-Worker-Allowed": "/",
    },
  });
}
