import { readFileSync } from "node:fs";
import path from "node:path";
import type { Game, Category } from "./types";
import type { SiteIdentity } from "./site-identity";
import type { SeoSettings } from "./types";
import type { PublicPage } from "./content-server";

// Server-only. Reads the JSON snapshot committed under src/data/fallback/
// — this is the "last known good" copy of everything a visitor-facing
// page needs, generated by scripts/generate-static-fallback.ts (wired
// into `npm run prebuild`, so it's refreshed automatically on every
// deploy) and shipped as part of the app bundle itself rather than kept
// only in Supabase.
//
// This is the layer every data-fetching function in games-server.ts,
// content-server.ts, site-identity.ts, and seo-settings.ts falls back to
// when a live Supabase read throws (network error, DNS failure, timeout
// — see timeout-fetch.ts) *and* there's no warm in-memory cache entry to
// serve instead (fragment-cache.ts / metadata-cache.ts already handle
// the warm-cache case; this covers a cold start / fresh instance / fresh
// deploy during an outage, which an in-memory cache can never help with).
//
// Read with plain fs, not fetch or an ORM: these files are small (a few
// hundred KB at most for a catalog of a few thousand games), bundled at
// build time, and read at most once per file per server instance thanks
// to the in-memory memoization below — there's no reason to make this
// async or pay a network round trip for data that's already sitting on
// local disk.

const FALLBACK_DIR = path.join(process.cwd(), "src", "data", "fallback");

// Per-instance memoization: the snapshot is immutable for the lifetime
// of a running server instance (it only changes on the next deploy), so
// re-reading the same file from disk on every request would be pure
// waste. Keyed on globalThis like fragment-cache.ts / metadata-cache.ts,
// for the same "survive dev-mode hot reload" reason.
interface StaticFallbackGlobals {
  cache: Map<string, unknown>;
}
const globalForStaticFallback = globalThis as unknown as { __staticFallback?: StaticFallbackGlobals };
function cache(): StaticFallbackGlobals {
  if (!globalForStaticFallback.__staticFallback) {
    globalForStaticFallback.__staticFallback = { cache: new Map() };
  }
  return globalForStaticFallback.__staticFallback;
}

function readJson<T>(filename: string, fallback: T): T {
  const key = filename;
  const g = cache();
  if (g.cache.has(key)) return g.cache.get(key) as T;

  try {
    const raw = readFileSync(path.join(FALLBACK_DIR, filename), "utf-8");
    const parsed = JSON.parse(raw) as T;
    g.cache.set(key, parsed);
    return parsed;
  } catch (err) {
    // Missing/corrupt snapshot file — shouldn't happen (every file below
    // is seeded with a valid empty/default value in the repo), but this
    // must never be the thing that throws during an outage, so degrade
    // to the caller's own last-resort default instead.
    console.error(`[static-fallback] Failed to read ${filename}, using built-in default:`, err);
    g.cache.set(key, fallback);
    return fallback;
  }
}

export function fallbackGames(): Game[] {
  return readJson<Game[]>("games.json", []);
}

export function fallbackCategories(): Category[] {
  return readJson<Category[]>("categories.json", []);
}

export function fallbackSiteIdentity(): Partial<SiteIdentity> | null {
  return readJson<Partial<SiteIdentity> | null>("site-identity.json", null);
}

export function fallbackSeoSettings(): Partial<SeoSettings> | null {
  return readJson<Partial<SeoSettings> | null>("seo-settings.json", null);
}

/** Slug -> page content. Always includes "about" and "contact" (seeded
 * with the same copy the page components already hardcode as their own
 * inline fallback — see src/app/about/page.tsx / src/app/contact/page.tsx
 * — so nothing regresses even before the generator script is ever run
 * against a real project), plus every other page the generator found
 * with show_in_nav = true at snapshot time. */
export function fallbackPages(): Record<string, PublicPage> {
  return readJson<Record<string, PublicPage>>("pages.json", {});
}

export function fallbackGameBySlug(slug: string): Game | null {
  return fallbackGames().find((g) => g.slug === slug) ?? null;
}

export function fallbackCategoryBySlug(slug: string): Category | null {
  return fallbackCategories().find((c) => c.slug === slug) ?? null;
}

export function fallbackPageBySlug(slug: string): PublicPage | null {
  return fallbackPages()[slug] ?? null;
}
