import type { SupabaseClient } from "@supabase/supabase-js";
import JSZip from "jszip";
import { CONTENT_TABLES } from "./content-tables";
import { validateMigrationManifest, type MigrationManifest } from "./manifest";
import { planContentRestore, restoreContentBackup, type RestoreSummary } from "./content-backup";
import type { StorageBucketSummary } from "./manifest";

export class MigrationValidationError extends Error {
  errors: string[];
  warnings: string[];
  constructor(errors: string[], warnings: string[] = []) {
    super(errors[0] ?? "Migration package validation failed.");
    this.name = "MigrationValidationError";
    this.errors = errors;
    this.warnings = warnings;
  }
}

export interface ParsedMigrationZip {
  manifest: MigrationManifest;
  data: Record<string, unknown[]>;
  storageBuckets: {
    id: string;
    public: boolean;
    fileSizeLimit: number | null;
    allowedMimeTypes: string[] | null;
    objectCount: number;
  }[];
  hasStorageFiles: boolean;
  schemaFileCount: number;
  appFileCount: number;
}

/** Unzips and structurally validates an uploaded Complete Migration
 * package — reads manifest.json + database/data/*.json into memory, but
 * writes nothing. This is deliberately the *only* thing this app does
 * with an uploaded ZIP's contents besides the controlled data-restore
 * below: it never executes anything from database/schema/*.sql or
 * treats any file in the ZIP as code to run — see the migration
 * report's Security section for why. */
export async function parseAndValidateMigrationZip(
  zipBuffer: Buffer,
  currentSchemaVersion: string
): Promise<ParsedMigrationZip> {
  let zip: JSZip;
  try {
    zip = await JSZip.loadAsync(zipBuffer);
  } catch {
    throw new MigrationValidationError(["Could not read this file as a ZIP archive."]);
  }

  const manifestEntry = zip.file("manifest.json");
  if (!manifestEntry) {
    throw new MigrationValidationError(["This ZIP has no manifest.json — it wasn't generated by this app's Complete Site Migration export."]);
  }

  let manifest: unknown;
  try {
    manifest = JSON.parse(await manifestEntry.async("string"));
  } catch {
    throw new MigrationValidationError(["manifest.json in this ZIP is not valid JSON."]);
  }

  const validation = validateMigrationManifest(manifest, currentSchemaVersion);
  if (!validation.ok) {
    throw new MigrationValidationError(validation.errors, validation.warnings);
  }
  const m = manifest as MigrationManifest;

  const data: Record<string, unknown[]> = {};
  for (const table of CONTENT_TABLES) {
    const entry = zip.file(`database/data/${table}.json`);
    if (!entry) continue;
    try {
      const parsed = JSON.parse(await entry.async("string"));
      if (Array.isArray(parsed)) data[table] = parsed;
    } catch {
      validation.warnings.push(`database/data/${table}.json in this ZIP is not valid JSON — that table will be skipped.`);
    }
  }

  const storageBuckets: ParsedMigrationZip["storageBuckets"] = [];
  for (const summary of m.includedStorageBuckets ?? []) {
    const entry = zip.file(`storage/buckets/${summary.id}.json`);
    if (!entry) continue;
    try {
      const parsed = JSON.parse(await entry.async("string")) as {
        id: string;
        public: boolean;
        fileSizeLimit: number | null;
        allowedMimeTypes: string[] | null;
        objects: unknown[];
      };
      storageBuckets.push({
        id: parsed.id,
        public: parsed.public,
        fileSizeLimit: parsed.fileSizeLimit,
        allowedMimeTypes: parsed.allowedMimeTypes,
        objectCount: parsed.objects?.length ?? 0,
      });
    } catch {
      validation.warnings.push(`storage/buckets/${summary.id}.json in this ZIP is not valid JSON — skipped.`);
    }
  }

  const schemaFileCount = Object.keys(zip.files).filter((f) => f.startsWith("database/schema/") && f.endsWith(".sql")).length;
  const appFileCount = Object.keys(zip.files).filter((f) => f.startsWith("src/") || f.startsWith("public/")).length;
  const hasStorageFiles = Object.keys(zip.files).some((f) => f.startsWith("storage/files/"));

  return {
    manifest: m,
    data,
    storageBuckets,
    hasStorageFiles,
    schemaFileCount,
    appFileCount,
  };
}

export interface MigrationRestorePlan {
  order: string[];
  rowPlan: { table: string; rowCount: number }[];
  bucketsToCreate: StorageBucketSummary["id"][];
  warnings: string[];
}

/** Builds the "here's exactly what will happen" preview for a migration
 * data-restore — same idea as planContentRestore, plus which storage
 * buckets would be newly created (never ones that already exist, and
 * never with different config than what's in the package). */
export async function planMigrationRestore(
  supabase: SupabaseClient,
  parsed: ParsedMigrationZip
): Promise<MigrationRestorePlan> {
  const { order, plan, warnings } = await planContentRestore(supabase, parsed.data);

  const { data: existingBuckets } = await supabase.storage.listBuckets();
  const existingIds = new Set((existingBuckets ?? []).map((b) => b.id));
  const bucketsToCreate = parsed.storageBuckets.filter((b) => !existingIds.has(b.id)).map((b) => b.id);

  return {
    order,
    rowPlan: plan,
    bucketsToCreate,
    warnings,
  };
}

export interface MigrationRestoreResult {
  dataRestore: RestoreSummary;
  bucketsCreated: string[];
  bucketErrors: { bucket: string; error: string }[];
}

/** Executes the migration's data-restore (identical mechanism to
 * Content Backup restore — same RPC, same FK-safe ordering) and
 * optionally creates any storage buckets from the package that don't
 * already exist in the destination project. Never touches
 * database/schema/*.sql or anything under src//public/ — those are for
 * the admin to apply/deploy manually, see migration-export.ts's
 * README_MIGRATION.md. */
export async function restoreMigrationData(
  supabase: SupabaseClient,
  parsed: ParsedMigrationZip,
  options: { tables?: string[]; createMissingBuckets?: boolean } = {}
): Promise<MigrationRestoreResult> {
  const dataRestore = await restoreContentBackup(supabase, parsed.data, { tables: options.tables });

  const bucketsCreated: string[] = [];
  const bucketErrors: { bucket: string; error: string }[] = [];

  if (options.createMissingBuckets) {
    const { data: existingBuckets } = await supabase.storage.listBuckets();
    const existingIds = new Set((existingBuckets ?? []).map((b) => b.id));

    for (const bucket of parsed.storageBuckets) {
      if (existingIds.has(bucket.id)) continue;
      const { error } = await supabase.storage.createBucket(bucket.id, {
        public: bucket.public,
        fileSizeLimit: bucket.fileSizeLimit ?? undefined,
        allowedMimeTypes: bucket.allowedMimeTypes ?? undefined,
      });
      if (error) {
        bucketErrors.push({ bucket: bucket.id, error: error.message });
      } else {
        bucketsCreated.push(bucket.id);
      }
    }
  }

  return { dataRestore, bucketsCreated, bucketErrors };
}
