import {
  LayoutGrid,
  LayoutDashboard,
  Gamepad2,
  MessageSquare,
  Home,
  Tag,
  FileText,
  Newspaper,
  Image as ImageIcon,
  GalleryHorizontal,
  Shapes,
  Video,
  Film,
  Search,
  Map,
  ScrollText,
  ClipboardList,
  Link2,
  Braces,
  Rss,
  BarChart3,
  Activity,
  TrendingUp,
  Users,
  HeartPulse,
  Plug,
  ShieldQuestion,
  ShieldCheck,
  HardDriveDownload,
  Ban,
  Flag,
  BadgeCheck,
  KeyRound,
  History,
  Languages,
  Coins,
  Type,
  MapPin,
  Sliders,
  Inbox,
  Archive,
  FolderKanban,
  ShieldAlert,
  MailWarning,
  MessagesSquare,
  UserX,
  AlertTriangle,
  Copyright,
  Gavel,
  Undo2,
  Scale,
  ListChecks,
  Zap,
  Wrench,
  Palette,
  ListTree,
  Megaphone,
  FileWarning,
  Grid3x3,
  ClipboardCheck,
  Database,
  Gauge,
  Globe,
  Cpu,
  Layers3,
  FileCode,
  Network,
  Lock,
  Rocket,
  BrainCircuit,
  Minimize2,
  Fingerprint,
  Star,
  type LucideIcon,
} from "lucide-react";

export const adminNavIcons: Record<string, LucideIcon> = {
  layoutDashboard: LayoutDashboard,
  layoutGrid: LayoutGrid,
  gamepad2: Gamepad2,
  messageSquare: MessageSquare,
  home: Home,
  tag: Tag,
  fileText: FileText,
  newspaper: Newspaper,
  image: ImageIcon,
  galleryHorizontal: GalleryHorizontal,
  shapes: Shapes,
  video: Video,
  film: Film,
  search: Search,
  map: Map,
  scrollText: ScrollText,
  clipboardList: ClipboardList,
  link2: Link2,
  braces: Braces,
  rss: Rss,
  barChart3: BarChart3,
  activity: Activity,
  trendingUp: TrendingUp,
  users: Users,
  heartPulse: HeartPulse,
  plug: Plug,
  shieldQuestion: ShieldQuestion,
  shieldCheck: ShieldCheck,
  hardDriveDownload: HardDriveDownload,
  ban: Ban,
  flag: Flag,
  badgeCheck: BadgeCheck,
  keyRound: KeyRound,
  history: History,
  languages: Languages,
  coins: Coins,
  type: Type,
  mapPin: MapPin,
  sliders: Sliders,
  inbox: Inbox,
  archive: Archive,
  folderKanban: FolderKanban,
  shieldAlert: ShieldAlert,
  mailWarning: MailWarning,
  messagesSquare: MessagesSquare,
  userX: UserX,
  alertTriangle: AlertTriangle,
  copyright: Copyright,
  gavel: Gavel,
  undo2: Undo2,
  scale: Scale,
  listChecks: ListChecks,
  zap: Zap,
  wrench: Wrench,
  palette: Palette,
  listTree: ListTree,
  megaphone: Megaphone,
  fileWarning: FileWarning,
  grid3x3: Grid3x3,
  clipboardCheck: ClipboardCheck,
  database: Database,
  gauge: Gauge,
  globe: Globe,
  cpu: Cpu,
  layers3: Layers3,
  fileCode: FileCode,
  network: Network,
  lock: Lock,
  rocket: Rocket,
  brainCircuit: BrainCircuit,
  minimize2: Minimize2,
  fingerprint: Fingerprint,
  star: Star,
};

export function AdminIcon({ name, size = 17 }: { name: string; size?: number }) {
  const Icon = adminNavIcons[name] ?? Database;
  return <Icon size={size} />;
}
