import { NextResponse } from "next/server";
import { z } from "zod";
import { requireAdmin } from "@/lib/supabase/route-auth";
import { logAdminAction } from "@/lib/supabase/admin-action-log";
import { apiError } from "@/lib/api-error";

// Backup filenames are generated by the automation system and look like:
// "backup-2026-08-07T03-12-00.000Z.json" or the same with ".enc" appended.
// The Supabase storage SDK treats the `name` param as a path inside the bucket,
// so any "name" that contains a path separator or ".." could theoretically reach
// a different object.  Lock this down to a safe subset: alphanumerics, hyphens,
// underscores, dots, and the colon that appears in ISO timestamps — no slashes,
// no backslashes, no null bytes.
const SAFE_FILENAME_RE = /^[\w.\-:]+$/;

const paramsSchema = z.object({
  name: z
    .string()
    .min(1)
    .max(200)
    .regex(SAFE_FILENAME_RE, "Backup name contains disallowed characters."),
});

/** GET /api/admin/security/backups/:name — a short-lived signed URL to
 * download the raw backup file (still encrypted if it was uploaded
 * encrypted — this is a raw download, not a decrypt-on-the-fly). */
export async function GET(_request: Request, { params }: { params: Promise<{ name: string }> }) {
  const parsedParams = paramsSchema.safeParse(await params);
  if (!parsedParams.success) {
    return NextResponse.json({ error: "Invalid backup name." }, { status: 400 });
  }

  const auth = await requireAdmin();
  if (!auth.ok) {
    return NextResponse.json({ error: auth.message }, { status: auth.status });
  }
  const { supabase } = auth.ctx;

  const { data, error } = await supabase.storage
    .from("automation-backups")
    .createSignedUrl(parsedParams.data.name, 60);

  if (error || !data) {
    // Previously this returned a generic message with nothing logged
    // anywhere — a real failure here (missing bucket, missing storage
    // policy, expired session, wrong file name) was completely
    // unobservable. Route it through apiError() like every other admin
    // route so the actual Supabase/storage error lands in the server
    // logs, while the client still only ever sees the safe message.
    return apiError(error ?? new Error("createSignedUrl returned no data"), "Failed to create download link.");
  }
  return NextResponse.json({ url: data.signedUrl });
}

/** DELETE /api/admin/security/backups/:name */
export async function DELETE(_request: Request, { params }: { params: Promise<{ name: string }> }) {
  const parsedParams = paramsSchema.safeParse(await params);
  if (!parsedParams.success) {
    return NextResponse.json({ error: "Invalid backup name." }, { status: 400 });
  }

  const auth = await requireAdmin();
  if (!auth.ok) {
    return NextResponse.json({ error: auth.message }, { status: auth.status });
  }
  const { supabase, user } = auth.ctx;

  const { error } = await supabase.storage.from("automation-backups").remove([parsedParams.data.name]);
  if (error) {
    return apiError(error, "Failed to delete backup.");
  }

  await logAdminAction(supabase, user, {
    action: "backup_deleted",
    targetType: "backup",
    targetId: parsedParams.data.name,
    summary: `Deleted backup file "${parsedParams.data.name}".`,
  });

  return NextResponse.json({ ok: true });
}
