import Link from "next/link";
import { ChevronRight } from "lucide-react";

export interface BreadcrumbTrailItem {
  name: string;
  href?: string;
}

/** Visible breadcrumb trail — pairs with the BreadcrumbList JSON-LD
 * generated by src/lib/seo.ts's breadcrumbSchema() for the same items, so
 * the on-page trail and the structured data never disagree (a common SEO
 * audit flag when they drift apart). The last item renders as plain text
 * (the current page), everything before it as a link. */
export function Breadcrumbs({ items }: { items: BreadcrumbTrailItem[] }) {
  if (items.length === 0) return null;

  return (
    <nav aria-label="Breadcrumb" className="flex flex-wrap items-center gap-1 text-xs text-text-faint">
      {items.map((item, i) => {
        const isLast = i === items.length - 1;
        return (
          <span key={`${item.name}-${i}`} className="flex items-center gap-1">
            {i > 0 && <ChevronRight size={12} className="shrink-0 text-text-faint/60" aria-hidden />}
            {isLast || !item.href ? (
              <span className="font-medium text-white/80" aria-current={isLast ? "page" : undefined}>
                {item.name}
              </span>
            ) : (
              <Link href={item.href} className="transition-colors hover:text-white">
                {item.name}
              </Link>
            )}
          </span>
        );
      })}
    </nav>
  );
}
